name: "S3 Pattern Upload"
description: "Update S3 Bucket in AWS with a file pattern"
author: "Martin Miglio"
branding:
  icon: 'check-square'
  color: 'orange'
inputs:
  bucket:
    description: 'Bucket Name'
    default: ''
  package:
    description: 'Package to upload S3'
    default: ''
  key:
    description: 'Key'
    default: ''
  AWS_SECRET_KEY:
    description: 'AWS Secret Key'
    default: ''
  AWS_SECRET_ID:
    description: 'AWS Secret Key'
    default: ''
  AWS_REGION:
    description: 'AWS Region'
    default: ''
runs:
  using: 'node12'
  main: 'index.js'
