name: "S3 Pattern Upload"
description: "Update S3 Bucket in AWS with a file pattern"
author: "Martin Miglio"
branding:
  icon: "check-square"
  color: "yellow"
inputs:
  PATTERN:
    description: "Package to upload S3"
    default: ""
  DEST:
    description: "Key"
    default: ""
  AWS_BUCKET_NAME:
    description: "Bucket Name"
    default: ""
  AWS_SECRET_KEY:
    description: "AWS Secret Key"
    default: ""
  AWS_SECRET_ID:
    description: "AWS Secret Key"
    default: ""
  AWS_REGION:
    description: "AWS Region"
    default: ""
runs:
  using: "node16"
  main: "index.js"
